version: '3.9'
services:
  db:
    container_name: db
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql@14/data
  app:
    container_name: app
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
        - HOST=0.0.0.0
        - PORT=8080
        - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
        - SECRET_KEY=secret
    depends_on:
      - db
volumes:
  pgdata: